crime_reporting/Police/urls.py
from django.urls import path
from . import views

urlpatterns = [

 path("pmissing/",views.pmissing, name='pmissing'),
 path(" policehome/",views.policehome, name='policehome'),
 path("mostwanted/",views.mostwanted, name='mostwanted'),
 
 ]

crime_reporting/crime_reporting/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Usersapp.urls')),
    path('Usersapp/', include('Usersapp.urls')),
    path('Police/', include('Police.urls'))

    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crime_reporting/Police/models.py
from django.db import models
from PIL import Image

# Create your models here.
class Missing(models.Model):
    name = models.CharField(max_length=20)
    mobile = models.IntegerField(default=0)
    address = models.CharField(max_length=80)
    city = models.CharField(max_length=20)
    image = models.ImageField(upload_to='missing_people', blank=True)
    details = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)



class wanted(models.Model):
    uname = models.CharField(max_length=20)
    height = models.IntegerField(default=0)
    color = models.CharField(max_length=20)
    crime_type = models.CharField(max_length=20)
    crime_area = models.CharField(max_length=20)
    crime_spot = models.CharField(max_length=20)
    photo = models.ImageField(upload_to='wanted_people', blank=True,null=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.uname

    def save(self):
        super().save()

        img = Image.open(self.photo.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)

crime_reporting/Police/forms.py
from django import forms
from .models import Missing
class MissingForm(forms.ModelForm):
    name = forms.CharField(required=False)
    mobile = forms.IntegerField(required=False)
    address = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":15}),required=False)
    city = forms.CharField(required=False)
    details = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":15}),required=False)

    class Meta:
        model = Missing
        fields = '__all__'

crime_reporting/Police/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import wanted,Missing
# Create your views here.

def pmissing(request):
    if request.method == 'POST':
        name = request.POST["t1"]
        mobile = request.POST["t2"]
        address = request.POST["t3"]
        city = request.POST["t4"]
        image = request.FILES["imgfile"]
        details = request.POST["t6"]
        mst = Missing(name=name, mobile=mobile, address=address, city=city, image=image,details=details)
        mst.save()

    return render(request,'Police/missing.html')

def mostwanted(request):
    if request.method =='POST':
        uname = request.POST.get('name')
        height = request.POST.get('height')
        color = request.POST.get("color")
        crime_type = request.POST.get("crime_type")
        crime_area = request.POST.get("crime_area")
        crime_spot = request.POST.get("crime_spot")
        image = request.FILES.get("img")
        mst = wanted(uname=uname, height=height, color=color, crime_type=crime_type, crime_area=crime_area,crime_spot=crime_spot, photo=image)
        mst.save()
    return render(request,'Police/mostwanted.html')


def policehome(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'Police/phome.html', context)
    
    

crime_reporting/Police/templates/Police/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <style type="text/css">

.sidenav {
  /*height: 100%; Full-height: remove this if you want "auto" height */
  width: 290px; /* Set the width of the sidebar */
 /* position: fixed;  Fixed Sidebar (stay in place on scroll) */
   /* Stay at the top */
  left: 0;
  background-color:white; /* Black */
  overflow-x: hidden; /* Disable horizontal scroll */
  padding-top: 20px;
  height: 660px;
  float: left;
  box-shadow: 10px 10px 5px gray;
  margin-top: 30px; 
  border-radius: 10px;
}

/* The navigation menu links */
.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 18px;

  color: whitesmoke;
  display: block;
  border-radius: 10px;
  background-color: #428;
  margin-top: 25px;
  height: 52px;
  box-shadow: 10px 10px 5px gray;
  margin-left: 10px;
  margin-right: 10px;
}
.welcome{

  text-align: center;
  font-style: italic;
}

/* When you mouse over the navigation links, change their color */
.sidenav a:hover {
  color: #f1f1f1;
}

/* Style page content */
.main {
  margin-left: 260px; /* Same as the width of the sidebar */
  padding: 0px 10px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidebar (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

       
  
    .content-section {
      background: #ffffff;
      padding: 10px 20px;
      border: 1px solid #dddddd;
      border-radius: 3px;
      margin-bottom: 20px;
    }
    
    .article-title {
      color: #444444;
    }
    
    a.article-title:hover {
      color: #428bca;
      text-decoration: none;
    }
    
    .article-content {
      white-space: pre-line;
    }
  
    .article-metadata {
      padding-bottom: 1px;
      margin-bottom: 4px;
      border-bottom: 1px solid #e3e3e3
    }
    
    .article-metadata a:hover {
      color: #333;
      text-decoration: none;
    }
    
    .article-svg {
      width: 25px;
      height: 25px;
      vertical-align: middle;
    }
    
    .account-img {
      height: 125px;
      width: 125px;
      margin-right: 20px;
      margin-bottom: 16px;
    }
    
    .account-heading {
      font-size: 2.5rem;
    }
   
  
    
    
  
       
        
        </style>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'Usersapp/main.css' %}">

</head>
<body>
    <header class="site-header mt-2 ml-5">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" style = " height:240px;border-radius: 7px; width:1450px">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100 mr-4" src="{% static 'Usersapp/a.gif' %}" alt="First slide" style = " height:240px;border-radius: 7px; width:1000px">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100 mr-4" src="{% static 'Usersapp/b.png' %}" alt="Second slide" style = " height:240px;border-radius: 7px; width:1000px">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100 mr-4" src="{% static 'Usersapp/c.jfif' %}" alt="Third slide" style = " height:240px; width:1000px">
              </div> 
              </div></div>
              </header>
              <div class="sidenav ml-5 ">
                <h1 class="welcome">WELCOME</h1>
                <a href="{% url 'policehome' %}#">Profile</a>
                <a href="#">View Complaints</a>
                <a href="{% url 'pmissing' %}" style="height: 58px;">Upload Missing People Information</a>
                <a href="{% url 'mostwanted' %}"  style="height: 58px;">Upload Mostwanted People Information</a>
                <a href="#">Logout</a>
              </div>          


      {% if messages %}
      {% for message in messages %}
        <div  style = "  width:1450px" class=" ml-5 mt-1 alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
   

          {% block content %}
          
          
          {% endblock %}
       
        
      
     <!-- Footer -->
     <footer class="page-footer font-small blue bg-secondary text-white ml-5 mb-2 " style = " width:1450px;border-radius: 7px;">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3 bg-">© 2018 Copyright:
          <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
      
      </footer>
  <!-- Footer -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

crime_reporting/Police/templates/Police/missing.html
{% extends "Police/layout.html" %}
{% load crispy_forms_tags %}
{% block content %}
<html>
<head>
</head>
<body>

          
<div class="container mb-4" style="margin-top:30px; margin-left:530px; box-shadow: 10px 10px 5px grey;width:500px; height: 720px">
<form class="form-group" action="{% url 'pmissing' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Missing People</legend>
    <div id="div_id_name" class="form-group">
    <label for="id_name" class="col-form-label ">
      Name
    </label><input type="text"  name="t1"  class="textinput textInput form-control" id="id_name">
    </div>
      
        
    <div id="div_id_height" class="form-group">
        <label for="id_height" class="col-form-label ">
          Mobile
        </label><input type="text"  class="textinput textInput form-control" id="id_height" name="t2">
    </div>
    <div id="div_id_color" class="form-group">
        <label for="id_color" class="col-form-label ">
          Address
        </label><input type="text"  name="t3"  class="textinput textInput form-control" id="id_color">
        
     </div>
     
    <div id="div_id_crime_area" class="form-group">
            <label for="id_crime_area" class="col-form-label ">
              City
            </label><input type="text" class="textinput textInput form-control" id="id_crime_area" name="t4">
        </div>
        
    
   
        

     
        <div id="div_id_image" class="form-group">
           <label for="id_image" class="col-form-label  requiredField">
            Image<span class="asteriskField">*</span> </label>
             <div class=""> <input type="file" name="imgfile" accept="image/*" class="clearablefileinput" required id="id_image"> 
            </div> </div> 

            <div id="div_id_crime_spot" class="form-group">
                <label for="id_crime_spot" class="col-form-label ">
                  Details
                </label><input type="text" class="textinput textInput form-control" id="id_crime_spot" name="t6">
                </div>
    </fieldset>
            <div>
                <button class="btn btn-outline-info" type ="submit">Submit</button>
                </div>
   


</form>



</div>
</body>
</html>

{% endblock content %}

crime_reporting/Police/templates/Police/mostwanted.html
{% extends "Police/layout.html" %}
{% load crispy_forms_tags %}
{% block content %}
<html>
<head>
</head>
<body>

          
<div class="container mb-4" style="margin-top:30px; margin-left:530px; border-radius: 10px; box-shadow: 10px 10px 5px grey;width:450px; height: 820px">
<form class="form-group" action="{% url 'mostwanted' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Most Wanted</legend>
    <div id="div_id_name" class="form-group">
    <label for="id_name" class="col-form-label ">
      Name
    </label><input type="text"  name="name"  class="textinput textInput form-control" id="id_name">
    </div>
      
        
    <div id="div_id_height" class="form-group">
        <label for="id_height" class="col-form-label ">
          Height
        </label><input type="text"  class="textinput textInput form-control" id="id_height" name="height">
    </div>
    <div id="div_id_color" class="form-group">
        <label for="id_color" class="col-form-label ">
          Color
        </label><input type="text"  name="color"  class="textinput textInput form-control" id="id_color">
        
     </div>
     <div id="div_id_crime_type" class="form-group">
        <label for="id_crime_type" class="col-form-label ">
          Crime Type
        </label><select class="mdb-select form-control" name="crime_type">
  <option value="" disabled selected>Choose your option</option>
  <option value="1">robery</option>
  <option value="2">rape</option>
  <option value="3">mudrer</option>
</select>

        </div>
    <div id="div_id_crime_area" class="form-group">
            <label for="id_crime_area" class="col-form-label ">
              Crime Area
            </label><input type="text" class="textinput textInput form-control" id="id_crime_area" name="crime_area">
        </div>
        
    
    <div id="div_id_crime_spot" class="form-group">
        <label for="id_crime_spot" class="col-form-label ">
          Crime Spot
        </label><input type="text" class="textinput textInput form-control" id="id_crime_spot" name="crime_spot">
        </div>
        

     
        <div id="div_id_image" class="form-group">
           <label for="id_image" class="col-form-label  requiredField">
            Image<span class="asteriskField">*</span> </label>
             <div class=""> <input type="file" name="img" accept="image/*" class="clearablefileinput" required id="id_image"> 
            </div> </div> 
    </fieldset>
            <div>
                <button class="btn btn-outline-info" type ="submit">Submit</button>
                </div>
   


</form>



</div>
</body>
</html>

{% endblock content %}

crime_reporting/Police/templates/Police/phome.html
{% extends "Usersapp/layout2.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% for post in posts %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
    </div>
    <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
{% endblock content %}